--SNOWFLAKE CREATE SCRIPT
--SCHEMA V4
CREATE DATABASE IF NOT EXISTS SISU_OUTPUTS;

CREATE OR REPLACE TABLE ANALYSIS_RESULT_WATERFALL (
    ANALYSIS_ID BIGINT,
    ANALYSIS_RESULT_ID BIGINT,
    STEP_ID INTEGER,
    STEP_TYPE TEXT,
    FACTOR_0_DIMENSION TEXT,
    FACTOR_0_VALUE TEXT,
    FACTOR_1_DIMENSION TEXT,
    FACTOR_1_VALUE TEXT,
    FACTOR_2_DIMENSION TEXT,
    FACTOR_2_VALUE TEXT,
    STEP_IMPACT FLOAT,
    CUMULATIVE_IMPACT_BEFORE_STEP FLOAT,
    CUMULATIVE_IMPACT_AFTER_STEP FLOAT,
    OVERLAPPING_IMPACT FLOAT,
    CHANGE_IN_SIZE_SET1 FLOAT,
    CHANGE_IN_SIZE_SET2 FLOAT,
    CHANGE_IN_TYPE_SET1 FLOAT,
    CHANGE_IN_TYPE_SET2 FLOAT,
    SEGMENT_TEXT TEXT,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, STEP_ID)
);

--TABLE TO HOLD TREND RESULT DETAILS
CREATE OR REPLACE TABLE TREND_RESULT_DETAIL (
    ANALYSIS_ID BIGINT,
    ANALYSIS_RESULT_ID BIGINT,
    SUBGROUP_ID BIGINT,
    FACTOR_0_DIMENSION TEXT,
    FACTOR_0_VALUE TEXT,
    FACTOR_1_DIMENSION TEXT,
    FACTOR_1_VALUE TEXT,
    FACTOR_2_DIMENSION TEXT,
    FACTOR_2_VALUE TEXT,
    IMPACT FLOAT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    INTERCEPT FLOAT,
    SLOPE FLOAT,
    SIZE FLOAT,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, SUBGROUP_ID)
);

--TABLE TO HOLD ANALYSIS RESULT DETAILS
CREATE OR REPLACE TABLE ANALYSIS_RESULT_DETAIL (
    ANALYSIS_ID BIGINT,
    ANALYSIS_RESULT_ID BIGINT,
    SUBGROUP_ID BIGINT,
    CONFIDENCE TEXT,
    FACTOR_0_DIMENSION TEXT,
    FACTOR_0_VALUE TEXT,
    FACTOR_1_DIMENSION TEXT,
    FACTOR_1_VALUE TEXT,
    FACTOR_2_DIMENSION TEXT,
    FACTOR_2_VALUE TEXT,
    FACTOR_0_DIMENSION_FRIENDLY TEXT,
    FACTOR_1_DIMENSION_FRIENDLY TEXT,
    FACTOR_2_DIMENSION_FRIENDLY TEXT,
    FACTOR_0_VALUE_FRIENDLY TEXT,
    FACTOR_1_VALUE_FRIENDLY TEXT,
    FACTOR_2_VALUE_FRIENDLY TEXT,
    FACTOR_0_TEXT TEXT,
    FACTOR_1_TEXT TEXT,
    FACTOR_2_TEXT TEXT,
    SEGMENT_TEXT TEXT,
    CHANGE FLOAT,
    IMPACT FLOAT,
    IMPACT_MAGNITUDE FLOAT,
    IMPACT_RANK TEXT,
    SET1_SIZE FLOAT,
    SET2_SIZE FLOAT,
    SET1_VALUE FLOAT,
    SET2_VALUE FLOAT,
    PERCENT_CHANGE FLOAT,
    DIRECTION TEXT,
    DIRECTION_TEXT TEXT,
    ORIENTATION_MATCHES_METRIC TEXT,
    SEGMENT_ORDER SMALLINT,
    SEGMENT_ORDER_TEXT TEXT,
    INSIGHT_TEXT TEXT,
    CHANGE_IN_SIZE FLOAT,
    MIX_EFFECT FLOAT,
    NET_EFFECT FLOAT,
    NET_RELATIVE_EFFECT FLOAT,
    PERCENT_CHANGE_IN_SIZE FLOAT,
    RATE_EFFECT FLOAT,
    RELATIVE_PERCENT_CHANGE FLOAT,
    RELATIVE_CHANGE FLOAT,
    RELATIVE_MIX_EFFECT FLOAT,
    SEGMENT_NAME TEXT,
    SEGMENT_RANK TEXT,
    SEGMENT_HASH TEXT,
    UNWEIGHTED_CHANGE_IN_AVERAGE FLOAT,
    WEIGHT FLOAT,
    WEIGHTED_CHANGE_IN_SUM FLOAT,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, SUBGROUP_ID)
);

--TABLE TO HOLD TREND RESULT SUMMARY INFORMATION
CREATE OR REPLACE TABLE TREND_RESULT_SUMMARY (
    ANALYSIS_ID BIGINT,
    ANALYSIS_RESULT_ID BIGINT,
    REQUESTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    RUN_STATUS TEXT,
    RUN_TYPE TEXT,
    CURRENT_PERIOD_CARD_LABEL TEXT,
    CURRENT_PERIOD_DENOMINATOR_LABEL TEXT,
    CURRENT_PERIOD_PERCENT_CHANGE FLOAT,
    CURRENT_PERIOD_SLOPE FLOAT,
    PREVIOUS_PERIOD_CARD_LABEL TEXT,
    PREVIOUS_PERIOD_DENOMINATOR_LABEL TEXT,
    PREVIOUS_PERIOD_PERCENT_CHANGE FLOAT,
    PREVIOUS_PERIOD_SLOPE FLOAT,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID)
);

--TABLE TO HOLD ANALYSIS RESULT SUMMARY INFORMATION
CREATE OR REPLACE TABLE ANALYSIS_RESULT_SUMMARY (
    ANALYSIS_ID BIGINT,
    ANALYSIS_RESULT_ID BIGINT,
    REQUESTED_AT TIMESTAMP,
    COMPLETED_AT TIMESTAMP,
    RUN_STATUS TEXT,
    RUN_TYPE TEXT,
    TIMEFRAME TEXT,
    PREVIOUS_PERIOD_START TIMESTAMP,
    PREVIOUS_PERIOD_END TIMESTAMP,
    RECENT_PERIOD_START TIMESTAMP,
    RECENT_PERIOD_END TIMESTAMP,
    GROUP_A_NAME TEXT,
    GROUP_B_NAME TEXT,
    METRIC_TYPE_LABEL TEXT,
    PERCENT_CHANGE FLOAT,
    DIRECTION TEXT,
    SET1_CARD_LABEL TEXT,
    SET1_CATEGORY_FILTER TEXT,
    SET1_AVERAGE FLOAT,
    SET1_MIN FLOAT,
    SET1_MAX FLOAT,
    SET1_MEDIAN FLOAT,
    SET1_SUM FLOAT,
    SET1_SUMMARY_VALUE FLOAT,
    SET1_TOTAL_SIZE FLOAT,
    SET1_TOTAL_NUMERATOR FLOAT,
    SET1_TOTAL_DENOMINATOR FLOAT,
    SET1_MATCH_SIZE FLOAT,
    SET1_WEIGHT FLOAT,
    SET2_CARD_LABEL TEXT,
    SET2_CATEGORY_FILTER TEXT,
    SET2_AVERAGE FLOAT,
    SET2_MIN FLOAT,
    SET2_MAX FLOAT,
    SET2_MEDIAN FLOAT,
    SET2_SUM FLOAT,
    SET2_SUMMARY_VALUE FLOAT,
    SET2_TOTAL_SIZE FLOAT,
    SET2_TOTAL_NUMERATOR FLOAT,
    SET2_TOTAL_DENOMINATOR FLOAT,
    SET2_MATCH_SIZE FLOAT,
    SET2_WEIGHT FLOAT,
    LOAD_TS TIMESTAMP,
    CONSTRAINT PK PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID)
);

--TABLE TO HOLD ANALYSIS INFORMATION
CREATE OR REPLACE TABLE ANALYSIS (
    ANALYSIS_ID BIGINT PRIMARY KEY,
    ANALYSIS_NAME TEXT,
    ANALYSIS_TYPE TEXT,
    APPLICATION_URL TEXT,
    CREATED_AT TIMESTAMP,
    METRIC_ID BIGINT,
    METRIC_NAME TEXT,
    METRIC_DESIRED_DIRECTION TEXT,
    METRIC_UNIT TEXT,
    METRIC_UNIT_IS_PERCENTAGE INTEGER,
    METRIC_UNIT_IS_SUFFIX INTEGER,
    METRIC_UNIT_SCALE INTEGER,
    METRIC_UNIT_KMB TEXT,
    PROJECT_ID BIGINT,
    PROJECT_NAME TEXT,
    LOAD_TS TIMESTAMP
);


--DDL UPGRADE SCRIPT
--V3 --> V4
CREATE OR REPLACE TABLE ANALYSIS_RESULT_WATERFALL AS (
    SELECT
        ANALYSIS_ID,
        ANALYSIS_RESULT_ID,
        STEP_ID,
        STEP_TYPE,
        FACTOR_0_DIMENSION,
        FACTOR_0_VALUE,
        FACTOR_1_DIMENSION,
        FACTOR_1_VALUE,
        FACTOR_2_DIMENSION,
        FACTOR_2_VALUE,
        STEP_IMPACT,
        CUMULATIVE_IMPACT_BEFORE_STEP,
        CUMULATIVE_IMPACT_AFTER_STEP,
        OVERLAPPING_IMPACT,
        CHANGE_IN_SIZE_SET1,
        CHANGE_IN_SIZE_SET2,
        CHANGE_IN_TYPE_SET1,
        CHANGE_IN_TYPE_SET2,
        CAST(NULL AS TEXT) SEGMENT_TEXT,
        LOAD_TS
    FROM
        ANALYSIS_RESULT_WATERFALL
);

ALTER TABLE ANALYSIS_RESULT_WATERFALL ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, STEP_ID);


--V2 --> V3
ALTER TABLE ANALYSIS_RESULT_WATERFALL ADD COLUMN LOAD_TS TIMESTAMP;

CREATE OR REPLACE TABLE ANALYSIS_RESULT_DETAIL AS (
    SELECT
        ANALYSIS_ID,
        ANALYSIS_RESULT_ID,
        SUBGROUP_ID,
        CONFIDENCE,
        FACTOR_0_DIMENSION,
        FACTOR_0_VALUE,
        FACTOR_1_DIMENSION,
        FACTOR_1_VALUE,
        FACTOR_2_DIMENSION,
        FACTOR_2_VALUE,
        FACTOR_0_DIMENSION_FRIENDLY,
        FACTOR_1_DIMENSION_FRIENDLY,
        FACTOR_2_DIMENSION_FRIENDLY,
        FACTOR_0_VALUE_FRIENDLY,
        FACTOR_1_VALUE_FRIENDLY,
        FACTOR_2_VALUE_FRIENDLY,
        FACTOR_0_TEXT,
        FACTOR_1_TEXT,
        FACTOR_2_TEXT,
        SEGMENT_TEXT,
        CAST(NULL AS FLOAT) CHANGE,
        IMPACT,
        IMPACT_MAGNITUDE,
        IMPACT_RANK,
        SET1_SIZE,
        SET2_SIZE,
        SET1_VALUE,
        SET2_VALUE,
        PERCENT_CHANGE,
        DIRECTION,
        DIRECTION_TEXT,
        ORIENTATION_MATCHES_METRIC,
        SEGMENT_ORDER,
        SEGMENT_ORDER_TEXT,
        INSIGHT_TEXT,
        CHANGE_IN_SIZE,
        MIX_EFFECT,
        NET_EFFECT,
        NET_RELATIVE_EFFECT,
        PERCENT_CHANGE_IN_SIZE,
        RATE_EFFECT,
        RELATIVE_PERCENT_CHANGE,
        CAST(NULL AS FLOAT) RELATIVE_CHANGE,
        RELATIVE_MIX_EFFECT,
        SEGMENT_NAME,
        SEGMENT_RANK,
        SEGMENT_HASH,
        UNWEIGHTED_CHANGE_IN_AVERAGE,
        WEIGHT,
        WEIGHTED_CHANGE_IN_SUM,
        LOAD_TS
    FROM ANALYSIS_RESULT_DETAIL
);

CREATE OR REPLACE TABLE ANALYSIS AS (
    SELECT
        ANALYSIS_ID,
        ANALYSIS_NAME,
        ANALYSIS_TYPE,
        APPLICATION_URL,
        CREATED_AT,
        METRIC_ID,
        METRIC_NAME,
        METRIC_DESIRED_DIRECTION,
        CAST(NULL AS TEXT) METRIC_UNIT,
        CAST(NULL AS INTEGER) METRIC_UNIT_IS_PERCENTAGE,
        CAST(NULL AS INTEGER) METRIC_UNIT_IS_SUFFIX,
        CAST(NULL AS INTEGER) METRIC_UNIT_SCALE,
        CAST(NULL AS TEXT) METRIC_UNIT_KMB,
        PROJECT_ID,
        PROJECT_NAME,
        LOAD_TS
    FROM ANALYSIS
);

ALTER TABLE ANALYSIS ADD PRIMARY KEY (ANALYSIS_ID);

ALTER TABLE ANALYSIS_RESULT_DETAIL ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, SUBGROUP_ID);


--DDL UPGRADE SCRIPT
--V1 --> V2
CREATE OR REPLACE TABLE ANALYSIS AS (
    SELECT
        ANALYSIS_ID,
        ANALYSIS_NAME,
        ANALYSIS_TYPE,
        APPLICATION_URL,
        CREATED_AT,
        METRIC_ID,
        METRIC_NAME,
        CAST(NULL AS TEXT) METRIC_DESIRED_DIRECTION,
        PROJECT_ID,
        PROJECT_NAME,
        LOAD_TS
    FROM ANALYSIS
);

CREATE OR REPLACE TABLE ANALYSIS_RESULT_SUMMARY AS (
SELECT
    ANALYSIS_ID,
    ANALYSIS_RESULT_ID,
    REQUESTED_AT,
    COMPLETED_AT,
    RUN_STATUS,
    RUN_TYPE,
    CAST(NULL AS TEXT) TIMEFRAME,
    PREVIOUS_PERIOD_START,
    PREVIOUS_PERIOD_END,
    RECENT_PERIOD_START,
    RECENT_PERIOD_END,
    GROUP_A_NAME,
    GROUP_B_NAME,
    METRIC_TYPE_LABEL,
    PERCENT_CHANGE,
    CAST(NULL AS TEXT) DIRECTION,
    SET1_CARD_LABEL,
    SET1_CATEGORY_FILTER,
    SET1_AVERAGE,
    SET1_MIN,
    SET1_MAX,
    SET1_MEDIAN,
    SET1_SUM,
    SET1_SUMMARY_VALUE,
    SET1_TOTAL_SIZE,
    SET1_TOTAL_NUMERATOR,
    SET1_TOTAL_DENOMINATOR,
    SET1_MATCH_SIZE,
    SET1_WEIGHT,
    SET2_CARD_LABEL,
    SET2_CATEGORY_FILTER,
    SET2_AVERAGE,
    SET2_MIN,
    SET2_MAX,
    SET2_MEDIAN,
    SET2_SUM,
    SET2_SUMMARY_VALUE,
    SET2_TOTAL_SIZE,
    SET2_TOTAL_NUMERATOR,
    SET2_TOTAL_DENOMINATOR,
    SET2_MATCH_SIZE,
    SET2_WEIGHT,
    LOAD_TS
FROM ANALYSIS_RESULT_SUMMARY
);

CREATE OR REPLACE TABLE ANALYSIS_RESULT_DETAIL (
SELECT
    ANALYSIS_ID,
    ANALYSIS_RESULT_ID,
    SUBGROUP_ID,
    CONFIDENCE,
    FACTOR_0_DIMENSION,
    FACTOR_0_VALUE,
    FACTOR_1_DIMENSION,
    FACTOR_1_VALUE,
    FACTOR_2_DIMENSION,
    FACTOR_2_VALUE,
    CAST(NULL AS TEXT) FACTOR_0_DIMENSION_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_1_DIMENSION_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_2_DIMENSION_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_0_VALUE_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_1_VALUE_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_2_VALUE_FRIENDLY,
    CAST(NULL AS TEXT) FACTOR_0_TEXT,
    CAST(NULL AS TEXT) FACTOR_1_TEXT,
    CAST(NULL AS TEXT) FACTOR_2_TEXT,
    CAST(NULL AS TEXT) SEGMENT_TEXT,
    IMPACT,
    CAST(NULL AS FLOAT) IMPACT_MAGNITUDE,
    CAST(NULL AS TEXT) IMPACT_RANK
    SET1_SIZE,
    SET2_SIZE,
    SET1_VALUE,
    SET2_VALUE,
    CAST(NULL AS FLOAT) PERCENT_CHANGE,
    CAST(NULL AS TEXT) DIRECTION,
    CAST(NULL AS TEXT) DIRECTION_TEXT,
    CAST(NULL AS TEXT) ORIENTATION_MATCHES_METRIC,
    CAST(NULL AS SMALLINT) SEGMENT_ORDER,
    CAST(NULL AS TEXT) SEGMENT_ORDER_TEXT,
    CAST(NULL AS TEXT) INSIGHT_TEXT,
    CAST(NULL AS FLOAT) CHANGE_IN_SIZE,
    CAST(NULL AS FLOAT) MIX_EFFECT,
    CAST(NULL AS FLOAT) NET_EFFECT,
    CAST(NULL AS FLOAT) NET_RELATIVE_EFFECT,
    CAST(NULL AS FLOAT) PERCENT_CHANGE_IN_SIZE,
    CAST(NULL AS FLOAT) RATE_EFFECT,
    CAST(NULL AS FLOAT) RELATIVE_PERCENT_CHANGE,
    CAST(NULL AS FLOAT) RATE_CHANGE,
    CAST(NULL AS FLOAT) RELATIVE_MIX_EFFECT,
    CAST(NULL AS TEXT) SEGMENT_NAME,
    CAST(NULL AS INTEGER) SEGMENT_RANK,
    CAST(NULL AS TEXT) SEGMENT_HASH,
    CAST(NULL AS FLOAT) UNWEIGHTED_CHANGE_IN_AVERAGE,
    CAST(NULL AS FLOAT) WEIGHT,
    CAST(NULL AS FLOAT) WEIGHTED_CHANGE_IN_SUM,
    CAST(NULL AS TEXT) UNITS,
    LOAD_TS
FROM
    ANALYSIS_RESULT_DETAIL
);

ALTER TABLE ANALYSIS ADD PRIMARY KEY (ANALYSIS_ID);

ALTER TABLE ANALYSIS_RESULT_SUMMARY ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID);

ALTER TABLE ANALYSIS_RESULT_DETAIL ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, SUBGROUP_ID);

ALTER TABLE TREND_RESULT_SUMMARY ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID);

ALTER TABLE TREND_RESULT_DETAIL ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, SUBGROUP_ID);

ALTER TABLE ANALYSIS_RESULT_WATERFALL ADD PRIMARY KEY (ANALYSIS_ID, ANALYSIS_RESULT_ID, STEP_ID);

